# Plugins
plugins:          [jekyll-paginate, jekyll-gist]

# Dependencies
gems:             [jekyll-paginate]
markdown:         kramdown
highlighter:      Rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Alexander Spaulding
tagline:          'Full-Stack Developer'
description:      'A full stack Developer proficent in web and software technologies.'
url:              
baseurl:          /

author:
  name:           'Alexander Spaulding'
  url:            

paginate:         5

# Custom vars
version:          1.0.1

github:
  repo:           https://github.com/poole/hyde
