# Plugins
plugins:          [jekyll-paginate, jekyll-gist]

# Dependencies
gems:             [jekyll-paginate]
markdown:         kramdown
highlighter:      Rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Alexander Spaulding
tagline:          'Full-Stack Developer'
description:      'I am a full stack software and web developer that likes to explore as much as I can in the computer science field. 
  This blog will server as a collection of my experiences in hopes that other developers can find some use from them.'
url:              
baseurl:          /

author:
  name:           'Alexander Spaulding'
  url:            

paginate:         5

# Custom vars
version:          1.0.1

github:
  repo:           https://github.com/poole/hyde
